
QT_PARENT :=  /usr/local/

all: example

example:
	c++ -std=c++14 -O2 -Wall -W -D_REENTRANT -fPIE \
		-I$(QT_PARENT)/include/QtCore \
		-I$(QT_PARENT)/include/QtGui \
		-I. \
		-framework QtCore \
		-F /usr/local/lib/ \
		-o example example.cpp

example-output:
	c++ -std=c++14 -O2 -Wall -E -W -D_REENTRANT -fPIE \
		-I$(QT_PARENT)/include/QtCore \
		-I$(QT_PARENT)/include/QtGui \
		-I. \
		-o example-raw.cpp example.cpp

nim:
	nim cpp -c --nimCache:nimsrc/ example.nim
