
QT_PARENT :=  /usr/local/

all:
	c++ -std=c++14 -O2 -Wall -W -D_REENTRANT -fPIE \
		-I$(QT_PARENT)/include/QtCore \
		-I$(QT_PARENT)/include/QtGui \
		-I. \
		-framework QtCore \
		-F /usr/local/lib/ \
		-o example example.cpp

